export const contacts = [
  { id: "1", name: "James Anderson", email: "james@email.com" },
  { id: "2", name: "Emily Johnson", email: "emily@email.com" },
  { id: "3", name: "Michael Brown", email: "michael@email.com" },
  { id: "4", name: "Sarah Davis", email: "sarah@email.com" },
  { id: "5", name: "David Wilson", email: "david@email.com" },
  { id: "6", name: "Olivia Taylor", email: "olivia@email.com" },
  { id: "7", name: "Daniel Moore", email: "daniel@email.com" },
  { id: "8", name: "Jessica Clark", email: "jessica@email.com" },
  { id: "9", name: "Matthew Lee", email: "matthew@email.com" },
  { id: "10", name: "Emma Harris", email: "emma@email.com" },
  { id: "11", name: "William Walker", email: "william@email.com" },
  { id: "12", name: "Chloe Young", email: "chloe@email.com" },
  { id: "13", name: "Joshua Lewis", email: "joshua@email.com" },
  { id: "14", name: "Sophia Hall", email: "sophia@email.com" },
  { id: "15", name: "Christopher Scott", email: "christopher@email.com" },
  { id: "16", name: "Isabella King", email: "isabella@email.com" },
  { id: "17", name: "Andrew Allen", email: "andrew@email.com" },
  { id: "18", name: "Abigail Martin", email: "abigail@email.com" },
  { id: "19", name: "Ethan Wright", email: "ethan@email.com" },
  { id: "20", name: "Lily Thompson", email: "lily@email.com" },
]